@startuml
skinparam classAttributeIconSize 0

enum EstadoSolicitud {
  REGISTRADA
  CLASIFICADA
  PRIORIZADA
  ASIGNADA
  EN_GESTION
  CERRADA
}

enum Rol {
  ESTUDIANTE
  RESPONSABLE
  ADMINISTRADOR
}

enum TipoSolicitud {
  HOMOLOGACION
  CUPO
  CANCELACION
  OTRO
}

enum CanalOrigen {
  CORREO
  PRESENCIAL
  WEB
  SISTEMA_ANTIGUO
}

enum PrioridadSolicitud {
  BAJA
  MEDIA
  ALTA
  CRITICA
}

class Solicitud {
  - id: Long
  - descripcion: String
  - fechaCreacion: LocalDateTime
  - fechaActualizacion: LocalDateTime
  - estado: EstadoSolicitud
  - prioridad: PrioridadSolicitud
}

class HistorialSolicitud {
  - id: Long
  - fecha: LocalDateTime
  - accion: String
  - observacion: String
  - estadoAnterior: EstadoSolicitud
  - estadoNuevo: EstadoSolicitud
}

class AsignacionResponsable {
  - id: Long
  - fechaAsignacion: LocalDateTime
}

class Usuario {
  - id: Long
  - nombre: String
  - correo: String
  - password: String
  - activo: boolean
  - rol: Rol
}

Solicitud "1" --> "1" Usuario : solicitante
Solicitud "1" --> "0..1" Usuario : responsable

Solicitud "1" --> "*" HistorialSolicitud
HistorialSolicitud "*" --> "1" Usuario : usuarioAccion

Solicitud "1" --> "*" AsignacionResponsable
AsignacionResponsable "*" --> "1" Usuario : responsable

@enduml